In [ ]:
import os, sys 
#to be able to interact with Google Drive's operating system
from google.colab import drive 
#drive is a module that allows us use Python to interact with google drive
drive.mount('/content/gdrive') 
#mounting google drive allows us to work with its contents
nb_path = '/content/notebooks'
os.symlink('/content/gdrive/My Drive/Colab Notebooks', nb_path)
sys.path.insert(0, nb_path)  # or append(nb_path)
#The last three lines are what changes the path of the file.c

Mounted at /content/gdrive


Install the required package

In [ ]:
!pip install tigramite

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.3/197.3 KB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 51.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.6/41.6 MB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 90.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 21.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.39.1
    Uninstalling llvmlite-0.39.1:
      Successfully uninstalled llvmlite-0.39.1
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.3
    Uninstalling scipy-1.7.3:
      Successfully uninstalled scipy-1.7.3
  Attempting uninstall: numba
    Fo

Import requied libraries

In [ ]:
# Imports
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline     
## use `%matplotlib notebook` for interactive figures
# plt.style.use('ggplot')
#import sklearn
import tigramite
from tigramite import data_processing as pp
from tigramite import plotting as tp
from tigramite.pcmci import PCMCI
from tigramite.independence_tests import ParCorr, GPDC, CMIknn, CMIsymb

/usr/local/lib/python3.8/dist-packages/tigramite/plotting.py:26: UserWarning: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/tigramite/../versions.py'
  warnings.warn(str(e))
/usr/local/lib/python3.8/dist-packages/tigramite/independence_tests/gpdc.py:27: UserWarning: No module named 'dcor'
  warnings.warn(str(e))
/usr/local/lib/python3.8/dist-packages/tigramite/independence_tests/gpdc_torch.py:33: UserWarning: No module named 'dcor'
  warnings.warn(str(e))


Upload the dataset we are interested to find the lagged causal links

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 8.6.csv to 8.6.csv


In [ ]:
import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['8.6.csv']))# Dataset is now stored in a Pandas Dataframe

In [ ]:
df=df.to_numpy()
print(df)

[[0.85249568 0.73798506 3.08014479 ... 1.27512462 0.99610433 1.28460526]
 [0.74065437 1.30358272 3.00025122 ... 0.79403383 1.70333278 2.15804869]
 [0.99554533 1.02900932 3.02997898 ... 1.03390461 1.3709208  2.06991585]
 ...
 [0.84673939 2.12524169 6.68358741 ... 9.06152794 6.13396513 5.01976527]
 [0.58336823 1.96281714 6.53445317 ... 7.99052886 5.86271376 4.9270226 ]
 [0.50622461 1.47677908 7.74991918 ... 8.27075105 5.71970818 5.57552946]]


In [ ]:
# Initialize dataframe object, specify time axis and variable names
var_names = [r'$X^1$', r'$X^2$', r'$X^3$', r'$X^4$', r'$X^5$', r'$X^6$', r'$X^7$', r'$X^8$']
dataframe = pp.DataFrame(df, 
                         datatime = np.arange(len(df)), 
                         var_names=var_names)

Perform the test using the parameters: significance level of the CI tests, minimum and maximum period of lags. Record the lagged links for the further steps.

In [ ]:
cond_ind_test = CMIknn()
pcmci = PCMCI(dataframe=dataframe, cond_ind_test=cond_ind_test)
results = pcmci.run_pcmciplus(tau_min=0, tau_max=6, pc_alpha=0.05)
pcmci.print_results(results, alpha_level=0.05)


## Significant links at alpha = 0.05:

    Variable $X^1$ has 1 link(s):
        ($X^1$ -1): pval = 0.00000 | val =  0.067

    Variable $X^2$ has 2 link(s):
        ($X^1$ -1): pval = 0.00000 | val =  0.023
        ($X^2$ -1): pval = 0.02900 | val =  0.021

    Variable $X^3$ has 1 link(s):
        ($X^2$ -2): pval = 0.00400 | val =  0.013

    Variable $X^4$ has 1 link(s):
        ($X^3$  0): pval = 0.00100 | val =  0.024

    Variable $X^5$ has 4 link(s):
        ($X^4$ -6): pval = 0.00000 | val =  0.020
        ($X^5$ -3): pval = 0.00000 | val =  0.019
        ($X^6$  0): pval = 0.00100 | val =  0.016 | unclear orientation due to conflict
        ($X^5$ -1): pval = 0.02400 | val =  0.014

    Variable $X^6$ has 2 link(s):
        ($X^5$ -6): pval = 0.00000 | val =  0.070
        ($X^5$  0): pval = 0.00100 | val =  0.016 | unclear orientation due to conflict

    Variable $X^7$ has 1 link(s):
        ($X^6$ -1): pval = 0.00000 | val =  0.026

    Variable $X^8$ has 1 link(s):
     

133 mins

In [ ]:
cond_ind_test = CMIknn()
pcmci = PCMCI(dataframe=dataframe, cond_ind_test=cond_ind_test)
results = pcmci.run_pcmciplus(tau_min=1, tau_max=6, pc_alpha=0.05)
pcmci.print_results(results, alpha_level=0.05)


## Significant links at alpha = 0.05:

    Variable $X^1$ has 1 link(s):
        ($X^1$ -1): pval = 0.00000 | val =  0.067

    Variable $X^2$ has 2 link(s):
        ($X^1$ -1): pval = 0.00000 | val =  0.023
        ($X^2$ -1): pval = 0.02500 | val =  0.021

    Variable $X^3$ has 2 link(s):
        ($X^2$ -2): pval = 0.00000 | val =  0.019
        ($X^3$ -3): pval = 0.00300 | val =  0.015

    Variable $X^4$ has 2 link(s):
        ($X^2$ -2): pval = 0.00900 | val =  0.018
        ($X^3$ -3): pval = 0.03700 | val =  0.017

    Variable $X^5$ has 3 link(s):
        ($X^4$ -6): pval = 0.00000 | val =  0.022
        ($X^5$ -3): pval = 0.00000 | val =  0.020
        ($X^5$ -1): pval = 0.01900 | val =  0.014

    Variable $X^6$ has 1 link(s):
        ($X^5$ -6): pval = 0.00000 | val =  0.076

    Variable $X^7$ has 1 link(s):
        ($X^6$ -1): pval = 0.00000 | val =  0.049

    Variable $X^8$ has 1 link(s):
        ($X^6$ -1): pval = 0.02300 | val =  0.031


57.5 mins