In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [ ]:
!pip install tigramite==4.2.2.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 420 kB 5.8 MB/s 


In [ ]:
# Imports
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline     
## use `%matplotlib notebook` for interactive figures
# plt.style.use('ggplot')
import sklearn
import tigramite
from tigramite import data_processing as pp
from tigramite import plotting as tp
from tigramite.pcmci import PCMCI
from tigramite.independence_tests import ParCorr, GPDC, CMIknn, CMIsymb

/usr/local/lib/python3.7/dist-packages/tigramite/independence_tests/gpdc.py:16: UserWarning: No module named 'dcor'
  warnings.warn(str(e))
/usr/local/lib/python3.7/dist-packages/tigramite/independence_tests/gpdc_torch.py:18: UserWarning: No module named 'dcor'
  warnings.warn(str(e))


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving OT_dataset.csv to OT_dataset.csv


In [ ]:
df.head()

AttributeError: ignored

In [ ]:
import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['OT_dataset.csv']))# Dataset is now stored in a Pandas Dataframe

In [ ]:
df=df.to_numpy()
print(df)

[[0.49892973 1.         1.         ... 0.46753247 0.9350022  0.9486166 ]
 [0.7139889  0.93303572 0.07419902 ... 0.30769231 0.51932367 0.26086957]
 [0.65937869 0.81845238 0.58431705 ... 0.54945055 0.66425121 0.92869565]
 ...
 [0.30240073 0.06547621 0.         ... 0.13186813 0.07246377 0.06521739]
 [0.         0.4092262  0.25351323 ... 0.6945055  0.65217391 0.14347826]
 [0.64981531 0.         0.02782464 ... 0.30769231 0.23349436 0.1826087 ]]


In [ ]:
# Initialize dataframe object, specify time axis and variable names
var_names = [r'$X^1$', r'$X^2$', r'$X^3$', r'$X^4$', r'$X^5$', r'$X^6$', r'$X^7$', r'$X^8$', r'$X^9$', r'$X^10$', r'$X^11$', r'$X^12$']
dataframe = pp.DataFrame(df, 
                         datatime = np.arange(len(df)), 
                         var_names=var_names)

In [ ]:
!pip install ipython-autotime

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.6 MB 5.3 MB/s 


In [ ]:
%load_ext autotime


time: 577 µs (started: 2022-08-26 20:57:48 +00:00)


In [ ]:
cond_ind_test = CMIknn()
pcmci = PCMCI(dataframe=dataframe, cond_ind_test=cond_ind_test)
results = pcmci.run_pcmciplus(tau_min=1, tau_max=2, pc_alpha=0.05)
pcmci.print_results(results, alpha_level=0.05)


## Significant links at alpha = 0.05:

    Variable $X^1$ has 0 link(s):

    Variable $X^2$ has 1 link(s):
        ($X^10$ -1): pval = 0.01400 | val =  0.111

    Variable $X^3$ has 0 link(s):

    Variable $X^4$ has 0 link(s):

    Variable $X^5$ has 0 link(s):

    Variable $X^6$ has 1 link(s):
        ($X^6$ -1): pval = 0.01500 | val =  0.087

    Variable $X^7$ has 0 link(s):

    Variable $X^8$ has 0 link(s):

    Variable $X^9$ has 0 link(s):

    Variable $X^10$ has 0 link(s):

    Variable $X^11$ has 1 link(s):
        ($X^3$ -1): pval = 0.00300 | val =  0.078

    Variable $X^12$ has 1 link(s):
        ($X^9$ -2): pval = 0.01200 | val =  0.094
time: 6min 11s (started: 2022-08-26 20:57:51 +00:00)


In [ ]:
cond_ind_test = CMIknn()
pcmci = PCMCI(dataframe=dataframe, cond_ind_test=cond_ind_test)
results = pcmci.run_pcmciplus(tau_min=0, tau_max=2, pc_alpha=0.05)
pcmci.print_results(results, alpha_level=0.05)


## Significant links at alpha = 0.05:

    Variable $X^1$ has 1 link(s):
        ($X^9$  0): pval = 0.00600 | val =  0.089 | unoriented link

    Variable $X^2$ has 1 link(s):
        ($X^10$ -1): pval = 0.02800 | val =  0.087

    Variable $X^3$ has 0 link(s):

    Variable $X^4$ has 0 link(s):

    Variable $X^5$ has 1 link(s):
        ($X^6$  0): pval = 0.01200 | val =  0.103 | unoriented link

    Variable $X^6$ has 1 link(s):
        ($X^5$  0): pval = 0.01200 | val =  0.103 | unoriented link

    Variable $X^7$ has 0 link(s):

    Variable $X^8$ has 0 link(s):

    Variable $X^9$ has 1 link(s):
        ($X^1$  0): pval = 0.00600 | val =  0.089 | unoriented link

    Variable $X^10$ has 1 link(s):
        ($X^11$  0): pval = 0.00200 | val =  0.102 | unoriented link

    Variable $X^11$ has 1 link(s):
        ($X^10$  0): pval = 0.00200 | val =  0.102 | unoriented link

    Variable $X^12$ has 0 link(s):
time: 8min 52s (started: 2022-08-26 21:04:03 +00:00)
