In [1]:
import os, sys 
#to be able to interact with Google Drive's operating system
from google.colab import drive 
#drive is a module that allows us use Python to interact with google drive
drive.mount('/content/gdrive') 
#mounting google drive allows us to work with its contents
nb_path = '/content/notebooks'
os.symlink('/content/gdrive/My Drive/Colab Notebooks', nb_path)
sys.path.insert(0, nb_path)  # or append(nb_path)
#The last three lines are what changes the path of the file.c

Mounted at /content/gdrive


Install the required package

In [2]:
pip install dcor

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
!pip install tigramite==4.2.2.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 420 kB 5.2 MB/s 


Import requied libraries

In [4]:
# Imports
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline     
## use `%matplotlib notebook` for interactive figures
# plt.style.use('ggplot')
#import sklearn
import tigramite
from tigramite import data_processing as pp
from tigramite import plotting as tp
from tigramite.pcmci import PCMCI
from tigramite.independence_tests import ParCorr, GPDC, CMIknn, CMIsymb

/content/notebooks/tigramite/independence_tests/gpdc_torch.py:18: UserWarning: No module named 'gpytorch'
  warnings.warn(str(e))


Upload the dataset we are interested to find the lagged causal links

In [5]:
from google.colab import files
uploaded = files.upload()

Saving x4_8.csv to x4_8.csv


In [6]:
import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['x4_8.csv']))# Dataset is now stored in a Pandas Dataframe

In [7]:
df=df.to_numpy()
print(df)

[[ 1.3126035   1.16323107  3.19938133  8.5633589 ]
 [ 1.03157343  1.3628532   2.62679737 10.73762035]
 [ 1.42902199  1.99981431  3.58095084 12.94785724]
 ...
 [ 1.67562035  1.43879696  3.0108933  26.96230261]
 [ 1.49530623  1.0039338   2.11409598 26.36071241]
 [ 1.04609489  1.27580711  2.83068952 26.31902849]]


In [8]:
# Initialize dataframe object, specify time axis and variable names
var_names = [r'$X^1$', r'$X^2$', r'$X^3$', r'$X^4$']
dataframe = pp.DataFrame(df, 
                         datatime = np.arange(len(df)), 
                         var_names=var_names)

Perform the test using the parameters: significance level of the CI tests, minimum and maximum period of lags. Record the lagged links for the further steps.

In [10]:
cond_ind_test = CMIknn()
pcmci = PCMCI(dataframe=dataframe, cond_ind_test=cond_ind_test)
results = pcmci.run_pcmciplus(tau_min=0, tau_max=8, pc_alpha=0.05)
pcmci.print_results(results, alpha_level=0.05)


## Significant links at alpha = 0.05:

    Variable $X^1$ has 1 link(s):
        ($X^1$ -1): pval = 0.00000 | val =  0.072

    Variable $X^2$ has 2 link(s):
        ($X^3$  0): pval = 0.00000 | val =  0.028 | unclear orientation due to conflict
        ($X^1$ -2): pval = 0.00000 | val =  0.027

    Variable $X^3$ has 2 link(s):
        ($X^2$ -6): pval = 0.00000 | val =  0.031
        ($X^2$  0): pval = 0.00000 | val =  0.028 | unclear orientation due to conflict

    Variable $X^4$ has 1 link(s):
        ($X^3$ -8): pval = 0.00000 | val =  0.020


40.5 mins

In [9]:
cond_ind_test = CMIknn()
pcmci = PCMCI(dataframe=dataframe, cond_ind_test=cond_ind_test)
results = pcmci.run_pcmciplus(tau_min=1, tau_max=8, pc_alpha=0.05)
pcmci.print_results(results, alpha_level=0.05)


## Significant links at alpha = 0.05:

    Variable $X^1$ has 1 link(s):
        ($X^1$ -1): pval = 0.00000 | val =  0.072

    Variable $X^2$ has 3 link(s):
        ($X^1$ -2): pval = 0.00000 | val =  0.032
        ($X^2$ -1): pval = 0.00700 | val =  0.019
        ($X^2$ -6): pval = 0.01900 | val =  0.015

    Variable $X^3$ has 2 link(s):
        ($X^2$ -6): pval = 0.00000 | val =  0.044
        ($X^2$ -1): pval = 0.01300 | val =  0.015

    Variable $X^4$ has 1 link(s):
        ($X^3$ -8): pval = 0.00000 | val =  0.020


38 mins