In [ ]:
import os, sys 
#to be able to interact with Google Drive's operating system
from google.colab import drive 
#drive is a module that allows us use Python to interact with google drive
drive.mount('/content/gdrive') 
#mounting google drive allows us to work with its contents
nb_path = '/content/notebooks'
os.symlink('/content/gdrive/My Drive/Colab Notebooks', nb_path)
sys.path.insert(0, nb_path)  # or append(nb_path)
#The last three lines are what changes the path of the file.c

Mounted at /content/gdrive


Install the required package

In [ ]:
pip install dcor

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 KB 4.9 MB/s eta 0:00:00


In [ ]:
!python ‐‐version

python3: can't open file '‐‐version': [Errno 2] No such file or directory


In [ ]:
!python --version

Python 3.8.16


In [ ]:
!pip install tigramite

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.3/197.3 KB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 47.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.6/41.6 MB 20.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 97.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 19.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.39.1
    Uninstalling llvmlite-0.39.1:
      Successfully uninstalled llvmlite-0.39.1
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.3
    Uninstalling scipy-1.7.3:
      Successfully uninstalled scipy-1.7.3
  Attempting uninstall: numba
    Fo

Import requied libraries

In [ ]:
pip install scipy 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 15.8 MB/s eta 0:00:00


In [ ]:
# Imports
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline     
## use `%matplotlib notebook` for interactive figures
# plt.style.use('ggplot')
#import sklearn
import tigramite
from tigramite import data_processing as pp
from tigramite import plotting as tp
from tigramite.pcmci import PCMCI
from tigramite.independence_tests import ParCorr, GPDC, CMIknn, CMIsymb

/usr/local/lib/python3.8/dist-packages/tigramite/plotting.py:26: UserWarning: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/tigramite/../versions.py'
  warnings.warn(str(e))
/usr/local/lib/python3.8/dist-packages/tigramite/independence_tests/gpdc.py:27: UserWarning: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/tigramite/independence_tests/../../versions.py'
  warnings.warn(str(e))
/usr/local/lib/python3.8/dist-packages/tigramite/independence_tests/gpdc_torch.py:33: UserWarning: No module named 'gpytorch'
  warnings.warn(str(e))


Upload the dataset we are interested to find the lagged causal links

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 6.4.csv to 6.4.csv


In [ ]:
import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['6.4.csv']))# Dataset is now stored in a Pandas Dataframe

In [ ]:
df=df.to_numpy()
print(df)

[[0.69473664 0.91801249 3.31692859 2.15016505 2.30343021 0.73476627]
 [1.09423485 0.76219239 4.55820073 2.87640821 2.60925902 1.26020101]
 [0.83000437 0.9818808  2.92599833 1.93766464 3.81328974 1.25718525]
 ...
 [1.2576928  2.14422691 7.52318797 3.9743442  4.32834256 1.74177414]
 [1.19308421 1.80736728 6.54172814 3.6496399  5.20553967 1.68833947]
 [1.6027534  1.65337596 7.38663    4.42566693 4.86772865 2.35549116]]


In [ ]:
# Initialize dataframe object, specify time axis and variable names
var_names = [r'$X^1$', r'$X^2$', r'$X^3$', r'$X^4$', r'$X^5$', r'$X^6$']
dataframe = pp.DataFrame(df, 
                         datatime = np.arange(len(df)), 
                         var_names=var_names)

Perform the test using the parameters: significance level of the CI tests, minimum and maximum period of lags. Record the lagged links for the further steps.

In [ ]:
cond_ind_test = CMIknn()
pcmci = PCMCI(dataframe=dataframe, cond_ind_test=cond_ind_test)
results = pcmci.run_pcmciplus(tau_min=0, tau_max=4, pc_alpha=0.05)
pcmci.print_results(results, alpha_level=0.05)


## Significant links at alpha = 0.05:

    Variable $X^1$ has 1 link(s):
        ($X^1$ -1): pval = 0.00000 | val =  0.077

    Variable $X^2$ has 2 link(s):
        ($X^2$ -1): pval = 0.00000 | val =  0.045
        ($X^2$ -2): pval = 0.00900 | val =  0.027

    Variable $X^3$ has 2 link(s):
        ($X^2$ -2): pval = 0.00000 | val =  0.029
        ($X^3$ -3): pval = 0.00400 | val =  0.014

    Variable $X^4$ has 1 link(s):
        ($X^3$  0): pval = 0.00100 | val =  0.023

    Variable $X^5$ has 2 link(s):
        ($X^5$ -3): pval = 0.00000 | val =  0.040
        ($X^4$ -4): pval = 0.00000 | val =  0.034

    Variable $X^6$ has 2 link(s):
        ($X^5$  0): pval = 0.00000 | val =  0.038
        ($X^4$  0): pval = 0.03200 | val =  0.012

## Ambiguous triples (not used for orientation):

    [($X^5$  0), $X^6$, $X^4$]
    [($X^4$  0), $X^6$, $X^5$]


133 mins

In [ ]:
cond_ind_test = CMIknn()
pcmci = PCMCI(dataframe=dataframe, cond_ind_test=cond_ind_test)
results = pcmci.run_pcmciplus(tau_min=1, tau_max=4, pc_alpha=0.05)
pcmci.print_results(results, alpha_level=0.05)


## Significant links at alpha = 0.05:

    Variable $X^1$ has 1 link(s):
        ($X^1$ -1): pval = 0.00000 | val =  0.083

    Variable $X^2$ has 2 link(s):
        ($X^2$ -1): pval = 0.00000 | val =  0.045
        ($X^2$ -2): pval = 0.00600 | val =  0.027

    Variable $X^3$ has 2 link(s):
        ($X^2$ -2): pval = 0.00000 | val =  0.039
        ($X^3$ -3): pval = 0.00000 | val =  0.023

    Variable $X^4$ has 2 link(s):
        ($X^2$ -2): pval = 0.00000 | val =  0.037
        ($X^3$ -3): pval = 0.00900 | val =  0.019

    Variable $X^5$ has 2 link(s):
        ($X^4$ -4): pval = 0.00000 | val =  0.047
        ($X^5$ -3): pval = 0.00000 | val =  0.046

    Variable $X^6$ has 3 link(s):
        ($X^4$ -4): pval = 0.00000 | val =  0.022
        ($X^5$ -3): pval = 0.00000 | val =  0.021
        ($X^5$ -2): pval = 0.00500 | val =  0.020


57.5 mins